# This is a basic workflow to help you get started with Actions

name: Firebase Distribution

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: set up JDK 17
        uses: gradle/gradle-build-action@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Show version and commit info
        run: |
          echo "Version: $(grep 'versionName' app/build.gradle | awk '{print $2}' | tr -d '\"')"
          echo "Commit: ${{ github.sha }}"

      - name: Build and distribute to Firebase
        env:
          FIREBASE_APP_ID: candidato-ovedrincon
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GROUPS: testers
        run: ./gradlew appDistributionUploadRelease
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          ./gradlew assemble
