name: Firebase Distribution

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Get version from build.gradle
        id: get_version
        run: echo "version=$(grep 'versionName' app/build.gradle | awk '{print $2}' | tr -d '\"')" >> $GITHUB_ENV

      - name: Get last commit message
        id: commit_msg
        run: echo "commit_msg=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Show version and commit info
        run: |
          echo "Version: ${{ env.version }}"
          echo "Commit: ${{ env.commit_msg }}"

      - name: Build and distribute to Firebase
        env:
          FIREBASE_APP_ID: candidato-ovedrincon
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GROUPS: testers
          RELEASE_NOTES: "Versión: ${{ env.version }}, Commit: ${{ env.commit_msg }}"
        run: |
          ./gradlew assembleRelease
          ./gradlew appDistributionUploadRelease -PfirebaseAppDistribution.releaseNotes="${RELEASE_NOTES}"