name: Firebase Distribution

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Show version and commit info
        run: |
          echo "Version: $(grep 'versionName' app/build.gradle | awk '{print $2}' | tr -d '\"')"
          echo "Commit: ${{ github.sha }}"

      - name: Build and distribute to Firebase
        env:
          FIREBASE_APP_ID: candidato-ovedrincon
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GROUPS: testers
        run: |
          ./gradlew assembleRelease
          ./gradlew appDistributionUploadRelease